### PR TITLE
IGList: Add auto-fixes done by XCode 9.3.

### PR DESCRIPTION
**Pull request by Shachlan**
## Changes in this pull request

Issue fixed: #

### Checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [ ] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by StatusReport** [comment]
@Shachlan can't we just upgrade IGListKit? They've added a PR that fixes Xcode 9.3 issues.

**Comment by Shachlan** [comment]
@StatusReport, from what I see these fixes are not a part of their `master` branch.
 The "Minimum fixes for Xcode 9.3 build errors" commit doesn't update the `LastUpgradeCheck` value.

Regardless, I do think we should merge their branch into ours, but that's not the scope of this minor PR.

**Comment by barakwei** [comment]
I Agree, they actually had another PR with the fixes this PR suggests, but it wasn't merged in favor of another PR.
@Shachlan Feel free to send the PR that fixes this. We can later merge from their master as part of the usual update.

**Comment by Shachlan** [comment]
BTW, we do need to merge from their master before upgrading to XCode 9.3, since Release build on XCode 9.3 fails.

**Comment by StatusReport** [comment]
Done.

**Pull request merged**
